
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: app-web
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: app-web
    template:
      metadata:
        labels:
          app: app-web
      spec:
        containers:
        - name: app-web
          image: maze-app-web
          ports:
          - containerPort: 5000
  